---

- name: Apply Base Configs 
  hosts: physical
  gather_facts: no

  tasks:

    - name: Apply Base Configs
      eos_config:
        src: "configs/{{ inventory_hostname }}-base.cfg"
        replace: config
        save_when: always

