---

- name: diff running config against master 
  hosts: eos1
  gather_facts: no

  tasks:
    
    - name: diff the running config against a master config
      eos_config:
        diff_against: intended
        intended_config: "{{ lookup('file', './configs/eos1-base.cfg') }}"